### ISSUE TITLE
Default sound is sharp

### ISSUE THREAD

**Issue by riban-bw** [polluxsynth/audio-plugins#1]
The default sound that emits when the LV2 is hosted for the first time reacts to MIDI input with an audio output that is too high in frequency.

Running on Zynthian V5 Oram (arm64).
Commit: 50f0828c4dd18ec1901194cd51a9d778acbe0030 (current master).

**Comment by polluxsynth** [comment]
By 'too high', do you mean 'supersonic', 'several octaves above what one would consider a useful musical pitch' (i.e. a couple of thousand Hertz) or just 'slightly sharp' (like 50 cents or so) ?

**Comment by riban-bw** [comment]
Probably about a semitone. I will check more accurately later.

**Comment by polluxsynth** [comment]
Hm, that's about the difference between 44100 and 48000 as well. Thanks, I'll look into it.

**Comment by riban-bw** [comment]
I am running at 48000 FPS.

**Comment by polluxsynth** [comment]
That's good input, sounds there's a sample rate setting call that gets lost. (MiMi-d by default sets up 44100 just to set up something).

BTW the default sample rate for Zynthian is 44100 isn't it? Is it still set like in this thread?
https://discourse.zynthian.org/t/zynthian-s-sample-rate/557/6

**Comment by riban-bw** [comment]
I think you may be right. I see that the constructor sets samplerate to 44100 and I don't see anything that changes it. There is a callback to set samplerate if changed by host but this won't do anything whilst the plugin is active (distrho behaviour) and won't be called if the host does not change samplerate.

LV2 host will pass the samplerate to the plugin on instantiation and I believe distrho uses this by default so it may not be necessary to set it explicitly. You can retrieve it with `double Plugin::getSampleRate()`.

**Comment by riban-bw** [comment]
Zynthian is 44100 out of the box but I want to lobby for this to change. It has the advantage of reducing processing cycles which may improve performance. (I have run stuff at 32000 when 15kHz bandwith is sufficient, e.g. modelling old synths.) 48000 can be a simpler number to process which can reduce load. 48000 is the industry standard in most audio industries. (Only CDs use 44100 for a funny historical reason.) But mostly I currently want 48000 because I am adding Jamulus support that uses the Opus CODEC that only runs at 48000. (Opus supports fractions of this but Jamulus is fixed at 48000.)

**Comment by polluxsynth** [comment]
> LV2 host will pass the samplerate to the plugin on instantiation and I believe distrho uses this by default so it may not be necessary to set it explicitly. You can retrieve it with `double Plugin::getSampleRate()`.

Thanks for the research. Sounds like getSampleRate is the solution. I'll try to check it out this evening.
