### ISSUE TITLE
Feature request: Presets

### ISSUE THREAD

**Issue by riban-bw** [polluxsynth/audio-plugins#3]
Please provide a set of presets that can demonstrate some of the features of the synth. Using a computer or hardware device with limited controls makes sound design challenging. It would be good to be able to hear some good examples out-of-the-box.

LV2 can store presets in ttl files.

Zynthian can use LV2 presets. (It also allows saving user presets.)

Example LV2 preset format attached. (This is the default settings for a new, unchanged sound.)
[MiMi-d.presets.zip](https://github.com/polluxsynth/audio-plugins/files/14650100/MiMi-d.presets.zip)

**Comment by polluxsynth** [comment]
Fixed on master. There are now a handful of patches in the plugins/mimid/Presets directory, which are installed to /usr/local/lib/lv2/MiMi-d.presets.lv2 (i.e. parallel to the plugin directory /usr/local/lib/lv2/MiMi-d.lv2) when the make **install** target is invoked.
