### ISSUE TITLE
Remove or hide superfluous parameter controls

### ISSUE THREAD

**Issue by riban-bw** [polluxsynth/audio-plugins#4]
There are several parameters / controls exposed that appear superfluous, e.g. "Unused 1". These should be removed or hidden if required by the underlying engine to avoid excessive and confusing UI/

**Comment by polluxsynth** [comment]
Yeah, these should at least be renaned Debug 1 and 2. They were initially a carryover from Obxd but I've used them for testing various settings during development before implementing proper parameters.

**Comment by riban-bw** [comment]
As you describe in the forum, "Economy Mode" allows static (off) or dynamic (on) CPU load. The former provides consistent behaviour. The latter allows more processors to be loaded if not used simultaneously. Each has its benefit so I think the setting can be useful (although maybe it should be a configuration rather than a user parameter).

There is a flag in LV2 to hide parameters from the UI so if there are necessary parameters that are of little or no use to the user at runtime then this flag can be used. (It is something like not_on_gui.) Zynthian honours this flag. This could possibly be used for the debug controls too. You may be able to expose them during test with an alternative (private / local) ttl.

**Comment by polluxsynth** [comment]
I should mention, regarding Economy Mode, that there is still a slight potential variation depending on exactly what the plugin is doing. For instance, the antialiasing for the triangle and pulse waves take slightly more DSP than the sawtooth, and the antialiasing also consumes more DSP at high pitches. It's not a staggering difference, but one or two percent gong from deep bass to a couple of kilohertz for 8 voices.

**Comment by polluxsynth** [comment]
Fixed on master.
