### ISSUE TITLE
ttl issues

### ISSUE THREAD

**Issue by riban-bw** [polluxsynth/audio-plugins#9]
The LV2 ttl shows a default value outside the min/max range for oversample and economymode. Both have a range 0..1 but the default value for each is 10.

The oscillator pitch is implemented with scale points for every integer value. These should be another way to do this. I think it can be done by using rdfs:range atom:Int. I am not an LV2 / ttl expert so can't be sure of the best way to do this but there must be a way to define a parameter as an integer with min and max values. If Zynthian finds this it should create the enumerated range.

**Comment by polluxsynth** [comment]
Thanks for finding the faulty default values, these parameters should of course have a default value of 1.

I agree that using scale points for the oscillator pitch is a bit clumsy (and also seems to slow down the UI somewhat), although I think it actually works well in practice. I'll look into if it can be done another way.

**Comment by riban-bw** [comment]
Zynthian uses the LV2 property `world.ns.lv2.integer` to decide whether a port has an integer value and the property `world.ns.lv2.toggled` to decide whether to use 2 values (min & max) or enumerate between min & max. This may not be the only way, e.g. [rangeSteps](https://lv2plug.in/ns/ext/port-props#rangeSteps) may be the _correct / official_ way to do this but I don't know if Zynthian supports this. (It may be implicit in the underlying LV2 library - I haven't checked.)

This works (at least in Zynthian):
```
    [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 35 ;
        lv2:name "Pitch" ;
        lv2:symbol "osc1pitch" ;
        lv2:default 0 ;
        lv2:minimum 0 ;
        lv2:maximum 72 ;
        lv2:portProperty lv2:integer ;
        lv2:portProperty <http://lv2plug.in/ns/ext/port-props#expensive> ,
                         <http://kxstudio.sf.net/ns/lv2ext/props#NonAutomatable> ;
        pg:group <https://butoba.net/homepage/mimid.html#portGroup_g401_osc1> ;
    ] ,
```

**Comment by riban-bw** [comment]
You can also combine the port properties, e.g.
```
   [
        a lv2:InputPort, lv2:ControlPort ;
        lv2:index 35 ;
        lv2:name "Pitch" ;
        lv2:symbol "osc1pitch" ;
        lv2:default 0 ;
        lv2:minimum 0 ;
        lv2:maximum 72 ;
        lv2:portProperty lv2:integer ,
                         <http://lv2plug.in/ns/ext/port-props#expensive> ,
                         <http://kxstudio.sf.net/ns/lv2ext/props#NonAutomatable> ;
        pg:group <https://butoba.net/homepage/mimid.html#portGroup_g401_osc1> ;
    ] ,
```

**Comment by polluxsynth** [comment]
Thanks for the suggestion, this works great, so I'll use it for all the stepped integer parameters (osc pitch, voice count, bend range and global octaves).
